# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_design_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(372, 303)
        Form2.setSizeIncrement(QtCore.QSize(0, 0))
        Form2.setStyleSheet("background-color: rgb(143,188,143);")
        self.textEdit = QtWidgets.QTextEdit(Form2)
        self.textEdit.setGeometry(QtCore.QRect(30, 30, 181, 31))
        self.textEdit.setStyleSheet("background-color: rgb(152, 251, 152);\n"
"font: 16px;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form2)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 80, 181, 31))
        self.textEdit_2.setStyleSheet("background-color: rgb(152, 251, 152);\n"
"font: 16px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form2)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 130, 181, 31))
        self.textEdit_3.setStyleSheet("background-color: rgb(152, 251, 152);\n"
"font: 16px;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(Form2)
        self.textEdit_4.setGeometry(QtCore.QRect(30, 180, 181, 31))
        self.textEdit_4.setStyleSheet("background-color: rgb(152, 251, 152);\n"
"font: 16px;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton = QtWidgets.QPushButton(Form2)
        self.pushButton.setGeometry(QtCore.QRect(270, 230, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton {\n"
"background-color:rgb(30, 185, 30);\n"
"border-style: outset;\n"
"color: rgb(255, 255, 255);\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: beige;\n"
"font: 22px;\n"
"\n"
"padding: 6px;\n"
"}\n"
"#pushButton:pressed {\n"
"background-color:rgb(50, 205, 50);\n"
"border-style: inset;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form2)
        self.label.setGeometry(QtCore.QRect(250, 20, 41, 41))
        self.label.setStyleSheet("#label{ font: 28px;\n"
"text-align: center}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form2)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 51, 41))
        self.label_2.setStyleSheet("#label_2 { font: 28px;\n"
"text-align: center}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form2)
        self.label_3.setGeometry(QtCore.QRect(250, 120, 51, 41))
        self.label_3.setStyleSheet("#label_3 { font: 28px;\n"
"text-align: center}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form2)
        self.label_4.setGeometry(QtCore.QRect(250, 170, 51, 41))
        self.label_4.setStyleSheet("#label_4 { font: 28px;\n"
"text-align: center}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form2)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("#label_5 {\n"
"background-color: rgb(0,100,0);\n"
"border-style: outset;\n"
"color: rgb(255, 255, 255);\n"
"border-width: 2px;\n"
"border-color: beige;\n"
"font: 16px;\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        self.textEdit.setHtml(_translate("Form2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Имя</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Form2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Логин</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("Form2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Пароль</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("Form2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Подтвердить пароль</span></p></body></html>"))
        self.pushButton.setText(_translate("Form2", "Log IN"))
        self.label.setText(_translate("Form2", "<html><head/><body><p><span style=\" font-size:22pt;\">❌</span></p></body></html>"))
        self.label_2.setText(_translate("Form2", "<html><head/><body><p><span style=\" font-size:22pt;\">❌</span></p></body></html>"))
        self.label_3.setText(_translate("Form2", "<html><head/><body><p><span style=\" font-size:22pt;\">❌</span></p></body></html>"))
        self.label_4.setText(_translate("Form2", "<html><head/><body><p><span style=\" font-size:22pt;\">❌</span></p></body></html>"))
